name: deployment

on:
    push:
        branches:
            - master
            - main

env:
    CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
    CLOUD_RUN_REGION: asia-southeast1
    # project-name but it can be anything you want
    REPO_NAME: member-thebanana-co

jobs:
    build-and-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # This step is where our service account will be authenticated
            - uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  project_id: ${{ secrets.b }}
                  service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
                  service_account_email: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}

            - name: Enable the necessary APIs and enable docker auth
              run: |-
                  gcloud config set project $CLOUD_RUN_PROJECT_ID
                  gcloud services enable containerregistry.googleapis.com
                  gcloud services enable run.googleapis.com
                  gcloud --quiet auth configure-docker
            - name: Build and tag image
              run: |-
                  docker build . --tag "asia.gcr.io/$REPO_NAME:$GITHUB_SHA"
            - name: Push image to GCR
              run: |-
                  docker push asia.gcr.io/$REPO_NAME:$GITHUB_SHA
            - name: Deploy
              run: |-
                  gcloud components install --quiet
                  gcloud run deploy $REPO_NAME --image asia.gcr.io/$REPO_NAME:$GITHUB_SHA \
                  --project $CLOUD_RUN_PROJECT_ID \
                  --platform managed \
                  --region $CLOUD_RUN_REGION \
                  --allow-unauthenticated \
                  --quiet
